# Generated by Django 4.2.2 on 2023-07-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='online_shop/static/img/', verbose_name='image'),
        ),
    ]
